version: "3"
services:
    web:
        image: "gr1zzly/lab3.6"
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Vancouver123!"
            ACCEPT_EULA: "Y"